spring:
  application:
    name: product-service

  profiles:
    active: local # 위에서 준 product-service + "-" + local 이런식으로 붙는 듯.

  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

server:
  port: 0 # 임시 포트 지정. 이후 config 서버에서 받아와서 오버라이딩할 예정

management:
  endpoints:
    web:
      exposure:
        include: refresh



message: 'default message'